### ISSUE TITLE
Gettting Page not found, Initial connect to db do not work?

### ISSUE THREAD

**Issue by Shadowman4205** [feathersjs-ecosystem/feathers-mongodb#105]
Hello, i tried using this plugin with no succes

i have got this function

```
const service =  function() {
  const app = this;
  
  MongoClient.connect("mongodb://localhost:27017/feathers").then(client => {
    const db = client.db("EaCms");
    app.use(
      "/news",
      service({
        Model: db.collection("news")
      })
    );
  });
}

const app = feathers()

app
  .configure(hooks())
  .configure(rest())
  .configure(service)
  .configure(middleware);

export deafault app;
```

and i am getting

```
{
    "name": "NotFound",
    "message": "Page not found",
    "code": 404,
    "className": "not-found",
    "errors": {}
}
```
i tried doing this - commenting the connect part

```
const service =  function() {
  const app = this;
  /*
 MongoClient.connect("mongodb://localhost:27017/feathers").then(client => {
    const db = client.db("EaCms");
    app.use(
      "/news",
      service({
        Model: db.collection("news")
      })
    );
  });*/
 
 app.use("/testmongdb", function(req, res) {
    res.send(JSON.stringify(true));
  });
}
```
and i get the true response.

how use this  plugin? what am i missing? is it because of connect that is async?

**Comment by daffl** [comment]
The best way is to set the `service.Model` after the connection as shown in the [MongoDB adapter example](https://github.com/feathersjs-ecosystem/feathers-mongodb).

The issue is that you `app.configure(middleware)` probably sets up a `notFound` handler and the service (since db connection runs asynchronously) is setting up its middleware after.

Also see [this FAQ](https://docs.feathersjs.com/faq/readme.html#i-always-get-a-404-for-my-custom-middleware).

**Comment by Shadowman4205** [comment]
@daffl  you said something about  after connection, what do you mean, cause as i stated in the post i am doing it.

**Comment by daffl** [comment]
You are configuring your service before the middleware but the connection callback will run asynchronously _after_ the middleware has already been set up.

As shown in the example I already linked, the best way to avoid this would be to register the service and set the model once the connection is established:

```js
const service =  function() {
  const app = this;
  
  app.use(
    "/news",
    service({})
  );
  
  MongoClient.connect("mongodb://localhost:27017/feathers").then(client => {
    const db = client.db("EaCms");
    
    app.service("news").Model = db.collection("news");
  });
}

const app = feathers()

app
  .configure(hooks())
  .configure(rest())
  .configure(service)
  .configure(middleware);

export default app;
```

**Comment by Shadowman4205** [comment]
Ohhh i missed this. thanks! Now it is working, before closing.
Using postman
http://localhost:3000/api/news <- this working
http://localhost:3000/api/news?id=5a43c1e1162dea5dc8a264dd <- this is not working
http://localhost:3000/api/news?test=test<- this is working
http://localhost:3000/api/news/5a43c1e1162dea5dc8a264dd <- neither this working

do i have to do something else or this bug of lib?

**Comment by daffl** [comment]
See https://github.com/feathersjs/feathers/issues/757
