### ISSUE TITLE
How save date type string as  ISODate type field?

### ISSUE THREAD

**Issue by Shadowman4205** [feathersjs-ecosystem/feathers-mongodb#108]
I want save this 2017-11-24T11:52:57.000Z as ISODate("2017-11-24T11:52:57.000Z") on mongodb, which is getting save as string. How can i make it happen?
  
[edit]

ok  i did this before  passing  data to service.create(data)

```
data.date = new Date(2017-11-24T11:52:57.000Z);
service.create(data)
```
is there any way to do this auto ?  by checking if field's value is date type string ?

**Comment by daffl** [comment]
For data conversion [Feathers hooks](https://docs.feathersjs.com/api/hooks.html) can be used. In your case a `before` `create` hook that converts the `data`:

```js
app.service('myservice').hooks({
  before: {
    create(context) {
      if(typeof context.data.date === 'string') {
        context.data.date = new Date(context.data.date);
      }
    }
  }
});
```

Also see the guides on [hooks](https://docs.feathersjs.com/guides/basics/hooks.html) and [processing data in the chat application](https://docs.feathersjs.com/guides/chat/processing.html).
