### ISSUE TITLE
$select query field doesn't work in find() method

### ISSUE THREAD

**Issue by jansel369** [feathersjs-ecosystem/feathers-mongodb#110]
### Expected behavior
.find() method should return results with specified fields from  $select query

### Actual behavior
It returns all the fields of docs

### System configuration

Tell us about the applicable parts of your setup.

.find({ query: {
    $select: [ 'firstName' ],
} })

// returns the data with all of its fields

This works in previous version of mongodb  adapter with pretty much the same configuration.

**Module versions** (especially the part that's not working):
3.0.0

**Comment by daffl** [comment]
Are you sure you are not changing the query somehow in a hook? This is being tested in https://github.com/feathersjs-ecosystem/feathers-service-tests/blob/master/src/common-tests.js#L229 and I just double checked that it still works with latest master.

**Comment by jansel369** [comment]
I cloned this repo then made some test and they all work just fine with mongodb v3.6.2 . I tried using $select query to three different services of my project without any modification to query object of params but they give the same result of returning all the fields. Other query like $limit and $sort has no problem.

**Comment by Pogix3m** [comment]
starting from mongodb 3.4, it  use **.project()** for selecting fields

**Comment by jansel369** [comment]
After I changed the codes to 

`    if (filters.$select) {
      q = this.Model.find(query).project(this._getSelect(filters.$select));
    }
`
thanks to @Pogix3m  now finally works on my project without a problem. Some of the unit test associated with $select breaks for this module.

**Comment by daffl** [comment]
If the build is still passing I'd be happy to accept a pull request with that change.

**Comment by jansel369** [comment]
Seems like fixes for this issue has been made but not included to the latest module. Though I just prevent recreating a new cursor object.

**Comment by daffl** [comment]
Closed via #111
