### ISSUE TITLE
changeStreams Feature ?

### ISSUE THREAD

**Issue by abalad** [feathersjs-ecosystem/feathers-mongodb#112]
The prediction for implementation of changeStreams in this adptador

**Comment by daffl** [comment]
I have been thinking about implementing Oplog tailing (which I assume change streams are the successor for) but it will cause similar issues as https://github.com/feathersjs-ecosystem/feathers-rethinkdb/issues/76. Those issues (post processing after hooks vs. other after hooks) are quite complicated to solve and I am not entirely sure if it would be worthwhile. Feathers can make any database real-time as long as everything is used through the Feathers API so oplog tailing/change streams only really matter if the database is updated outside of Feathers and you still want to get Feathers real-time updates.

**Comment by abalad** [comment]
So I understand that yes it is very complicated, I just raised this question precisely because in RethinkDB you sending data directly from the database the FeatherJS API can respond with the updated / inserted data.

In Mongo it could be with ChangeStreams, but I think it really should be something a bit difficult to implement.
