### ISSUE TITLE
Perfom an aggregation pipline

### ISSUE THREAD

**Issue by cryax** [feathersjs-ecosystem/feathers-mongodb#114]
Can I build an aggregation pipeline via service.Model?
something like `service.Model.aggregate([{'$sample': {'size': 1 }}]);`

**Comment by Pogix3m** [comment]
Yes you can. Like
`
const results = await service.Model([
      {$match: {item_id: id}},
      {$group: {_id: null, total_quantity: {$sum: '$quantity'}}}
    ]).toArray();
`

You can check these:
- [aggregate](https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/)
- [pipeline](https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline/)

**Comment by daffl** [comment]
That sounds about right, thank you @Pogix3m!

**Comment by ericuldall** [comment]
I see how you would craft an aggregation in the server, but could you provide a basic example of how I would link this up with my client? Right now i'm using feathers-vuex. Is there some way to override the default find functionality using a before hook?

Any help here is appreciated as documentation on the topic is limited.

**Comment by ericuldall** [comment]
Here's what I have working for now and I'm not sure if this is the best way.

```
exports.ServiceAggregate = class ServiceAggregate {
    constructor (app) {
        this.app = app;
    }

    async find () {
      const response = await this.app.service('service').Model.aggregate([{...}]).toArray();
      return response;
    }
};
```

Then I set up the service to be called at `/service-aggregate`
