### ISSUE TITLE
$addToSet not working

### ISSUE THREAD

**Issue by cryax** [feathersjs-ecosystem/feathers-mongodb#116]
I got the error message below when trying to use $addToSet in patching a document
error:  GeneralError: The dollar ($) prefixed field '$addToSet' in '$addToSet' is not valid for storage.

**Comment by daffl** [comment]
How does the data look like and what version are you using?

**Comment by cryax** [comment]
Here's the log for the context
{ id: '5ac721b3d05b20da7095819c',
  data: 
   { '$addToSet': { collections: 1 },
     user_birth_year: '1992',
     last_updated_date: 2018-05-15T07:35:40.636Z },
  params: 
   { query: {},
     route: {},
     provider: 'rest',
     headers: 
      { host: 'localhost:3030',
        connection: 'keep-alive',
        'content-length': '92',
        'postman-token': '24a1234b-2894-6356-7439-e62330a1f040',
        'cache-control': 'no-cache',
        origin: 'chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo',
        'x-postman-interceptor-id': '25c763db-8be5-04e2-98e4-59daa6ab0dbd',
        'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36',
        'content-type': 'application/json',
        accept: '*/*',
        'accept-encoding': 'gzip, deflate, sdch, br',
        'accept-language': 'vi,en-US;q=0.8,en;q=0.6,en-GB;q=0.4',
        cookie: 'timezone=browser; theme=app-theme-dark; _ga=GA1.1.845106462.1521444242; mmsa-hosted=ca676116aefccedc150fee48b1732b11-20180419; cloud-user=1' } },
  type: 'before',
  service: 
   { Model: Collection { s: [Object] },
     id: '_id',
     events: [],
     paginate: { default: 10, max: 50 },
     find: [Function],
     get: [Function],
     create: [Function],
     patch: [Function],
     update: [Function],
     remove: [Function],
     hooks: [Function: hooks],
     _events: 
      { created: [Function],
        updated: [Function],
        removed: [Function],
        patched: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     setMaxListeners: [Function: setMaxListeners],
     getMaxListeners: [Function: getMaxListeners],
     emit: [Function: emit],
     addListener: [Function: addListener],
     on: [Function: addListener],
     prependListener: [Function: prependListener],
     once: [Function: once],
     prependOnceListener: [Function: prependOnceListener],
     removeListener: [Function: removeListener],
     removeAllListeners: [Function: removeAllListeners],
     listeners: [Function: listeners],
     rawListeners: [Function: rawListeners],
     listenerCount: [Function: listenerCount],
     eventNames: [Function: eventNames],
     publish: [Function: publish],
     _super: undefined,
     [Symbol(@feathersjs/transport-commons/publishers)]: {} },
  app: 
   { [EventEmitter: app]
     _events: 
      { mount: [Function: onmount],
        publish: [Function],
        connection: [Function],
        login: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     setMaxListeners: [Function: setMaxListeners],
     getMaxListeners: [Function: getMaxListeners],
     emit: [Function: emit],
     addListener: [Function: addListener],
     on: [Function: addListener],
     prependListener: [Function: prependListener],
     once: [Function: once],
     prependOnceListener: [Function: prependOnceListener],
     removeListener: [Function: removeListener],
     removeAllListeners: [Function: removeAllListeners],
     listeners: [Function: listeners],
     rawListeners: [Function: rawListeners],
     listenerCount: [Function: listenerCount],
     eventNames: [Function: eventNames],
     init: [Function: init],
     defaultConfiguration: [Function: defaultConfiguration],
     lazyrouter: [Function: lazyrouter],
     handle: [Function: handle],
     use: [Function],
     route: [Function: route],
     engine: [Function: engine],
     param: [Function: param],
     set: [Function: set],
     path: [Function: path],
     enabled: [Function: enabled],
     disabled: [Function: disabled],
     enable: [Function: enable],
     disable: [Function: disable],
     acl: [Function],
     bind: [Function],
     checkout: [Function],
     connect: [Function],
     copy: [Function],
     delete: [Function],
     get: [Function],
     head: [Function],
     link: [Function],
     lock: [Function],
     'm-search': [Function],
     merge: [Function],
     mkactivity: [Function],
     mkcalendar: [Function],
     mkcol: [Function],
     move: [Function],
     notify: [Function],
     options: [Function],
     patch: [Function],
     post: [Function],
     propfind: [Function],
     proppatch: [Function],
     purge: [Function],
     put: [Function],
     rebind: [Function],
     report: [Function],
     search: [Function],
     subscribe: [Function],
     trace: [Function],
     unbind: [Function],
     unlink: [Function],
     unlock: [Function],
     unsubscribe: [Function],
     all: [Function: all],
     del: [Function],
     render: [Function: render],
     listen: [Function],
     request: IncomingMessage { app: [Circular] },
     response: ServerResponse { app: [Circular] },
     cache: {},
     engines: {},
     settings: 
      { 'x-powered-by': true,
        etag: 'weak',
        'etag fn': [Function: generateETag],
        env: 'development',
        'query parser': 'extended',
        'query parser fn': [Function: parseExtendedQueryString],
        'subdomain offset': 2,
        'trust proxy': false,
        'trust proxy fn': [Function: trustNone],
        view: [Function: View],
        views: '/media/younet/DATA/dang/source_code/influencer-backend/views',
        'jsonp callback name': 'callback',
        host: 'localhost',
        port: 3030,
        public:,
        paginate: [Object],
        mongodb: 'mongodb://localhost:27017/test',
        authentication: [Object],
        mongoClient: [Promise],
        auth: [Object] },
     locals: { settings: [Object] },
     mountpath: '/',
     configure: [Function: configure],
     service: [Function: service],
     setup: [Function],
     version: '3.1.4',
     methods: [ 'find', 'get', 'create', 'update', 'patch', 'remove' ],
     mixins: 
      [ [Function: hookMixin],
        [Function: eventMixin],
        [Function],
        [Function],
        [Function] ],
     services: 
      { 'api/v1/authentication': [Object],
        'api/v1/influencers': [Object],
        'api/v1/collections': [Object],
        'api/v1/category': [Object],
        'api/v1/users': [Object],
        'api/v1/posts': [Object],
        'api/v1/roles': [Object] },
     providers: [ [Function] ],
     _setup: false,
     hookTypes: [ 'before', 'after', 'error', 'finally' ],
     hooks: [Function: hooks],
     eventMappings: 
      { create: 'created',
        update: 'updated',
        remove: 'removed',
        patch: 'patched' },
     _super: undefined,
     _router: 
      { [Function: router]
        params: {},
        _params: [],
        caseSensitive: false,
        mergeParams: undefined,
        strict: false,
        stack: [Array] },
     rest: 
      { find: [Function],
        get: [Function],
        create: [Function],
        update: [Function],
        patch: [Function],
        remove: [Function] },
     channel: [Function: channel],
     publish: [Function: publish],
     lookup: [Function: lookup],
     passport: 
      Authenticator {
        _key: 'passport',
        _strategies: [Object],
        _serializers: [],
        _deserializers: [],
        _infoTransformers: [],
        _framework: [Object],
        _userProperty: 'user',
        _sm: [SessionManager],
        Authenticator: [Function: Authenticator],
        Passport: [Function: Authenticator],
        Strategy: [Function],
        strategies: [Object],
        _feathers: [Object],
        createJWT: [Function: createJWT],
        verifyJWT: [Function: verifyJWT],
        options: [Function] },
     authenticate: [Function: bound ],
     _logger: undefined,
     log: [Function: log],
     info: [Function: info],
     warn: [Function: warn],
     error: [Function: error],
     debug: [Function: debug],
     io: 
      Server {
        nsps: [Object],
        parentNsps: Map {},
        _path: '/socket.io',
        _serveClient: true,
        parser: [Object],
        encoder: Encoder {},
        _adapter: [Function: Adapter],
        _origins: '*:*',
        sockets: [Namespace],
        eio: [Server],
        httpServer: [Server],
        engine: [Server] },
     _isSetup: true,
     [Symbol(@feathersjs/transport-commons/channels)]: {},
     [Symbol(@feathersjs/transport-commons/publishers)]: 
      { [Symbol(@feathersjs/transport-commons/all-events)]: [Function] },
     [Symbol(@feathersjs/transport-commons/router)]: 
      { _rootNode: [Node],
        _strictMode: undefined,
        _staticRoutesMap: [Object] } },
  method: 'patch',
  path: 'test/test' }
error:  GeneralError: The dollar ($) prefixed field '$addToSet' in '$addToSet' is not valid for storage.

**Comment by cryax** [comment]
I've just tried a simple patch and it works:
let data = {};
data.$addToSet = {collections: { $each: contextData.collections}};
data.$set = {'last_name': 'mama'};
await context.app.service('/api/test').patch(null, data, {});

context.data for this query is None so I guess I can't just put mongo operators like $set or $addToSet in context.data. Is that correct? and how to customize a query containing these operators?

**Comment by cryax** [comment]
Update package to latest version solved my problem.

**Comment by daffl** [comment]
It thought so. The fix was in #115
