### ISSUE TITLE
Update method shows deprecation warning

### ISSUE THREAD

**Issue by waltherjj** [feathersjs-ecosystem/feathers-mongodb#122]
### Steps to reproduce

- [] Generate basic feathers app (REST) with feathers-cli.
- [] Generate new MongoDB service with feathers-cli.
- [] Create new MongoDB database and collection, insert empty document.
- [] Run a put request to the mongodb-service endpoint with document id.

### Expected behavior
Document gets updated, no warning messages shown.

### Actual behavior
Document gets updated, but a deprecation warning is shown: 

> DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead

Reason: The update method should use updateOne internally.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
 "@feathersjs/express": "^1.2.6",
 "@feathersjs/feathers": "^3.2.2",
"feathers-mongodb": "^3.3.0",
MongoDB 3.6.7

**NodeJS version**:
8.12.0

**Operating System**:
Linux Mint 18

**Comment by Gerigot** [comment]
I've forked this version and adjusted the create (insert => insertMany insertOne ) deprecation version, if you want I can try to fix all of this kind of error and make a pull request let me know if it's ok

**Comment by daffl** [comment]
Yes, that is always very welcome.

**Comment by Gerigot** [comment]
OK I'll work on that, I've seen that updateOne and updateMany are quite different from the update itself.

**Comment by daffl** [comment]
Closed via #126
