### ISSUE TITLE
[Feature request] increase performances using bulk write

### ISSUE THREAD

**Issue by claustres** [feathersjs-ecosystem/feathers-mongodb#123]
When inserting, updating or deleting multiple documents at once I think the recommended and optimal way is to use http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#bulkWrite.

It can also helps implementing patching of multiple objects using different filter queries at the same time.

So I wonder if you think it is worth considering using it to standardize the underlying interface ?

It might also help to solve https://github.com/feathersjs-ecosystem/feathers-mongodb/issues/122.

**Comment by daffl** [comment]
I believe this has also been addressed via #126

**Comment by Gerigot** [comment]
I haven't used bulk write in my fix so I will check if there are performance differences between that and insertMany/updateMany. 

In case I'll make another PR.

**Comment by claustres** [comment]
I think this is already a great work you did, I don't think that there will be a lot of differences.

What could be interesting is that it can also helps implementing patching of multiple objects using different filter queries at the same time.

**Comment by claustres** [comment]
You can make multiple updateOne/updateMany operations, each with a different filter: https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/#updateone-and-updatemany.
