### ISSUE TITLE
Still seeing the deprecation messages even after updating to 3.4.0

### ISSUE THREAD

**Issue by heinrichdonabad** [feathersjs-ecosystem/feathers-mongodb#128]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Closing since the build for the latest version does not show any deprecation warnings. It may be that your own code is still using deprecated functionality.
