### ISSUE TITLE
BadRequest: Invalid query parameter $geoWithin

### ISSUE THREAD

**Issue by cryax** [feathersjs-ecosystem/feathers-mongodb#141]
{ location:  { '$geoWithin':   { '$centerSphere': [ [40.848688, -73.856029 ], 5/3963.2 ] } } }
I used the above query to find all locations around a specific location within 5 miles, it works when I ran the command in mongodb console but it threw this error in feathersjs:
error: BadRequest: Invalid query parameter $geoWithin

**Comment by daffl** [comment]
Non standard query syntax [has to be whitelisted explicitly](https://crow.docs.feathersjs.com/migrating.html#whitelisting) as shown in the [options documentation](https://github.com/feathersjs-ecosystem/feathers-mongodb#serviceoptions).
