### ISSUE TITLE
Update data using custom identifier

### ISSUE THREAD

**Issue by sujeetbuddiga** [feathersjs-ecosystem/feathers-mongodb#146]
Hi, thanks for creating this awesome library available.

I just wanted to know in the case of using the service.update(id,data) method, is it possible to send the unique identifier aka **id** as **UID**

I meant something like `service.update({UID:"XXX12345"},{items:[]})`

Thanks,
Sujeet

**Comment by daffl** [comment]
Yes but only with `patch` where [the id can be null](https://docs.feathersjs.com/api/databases/common.html#adapterpatchid-data-params):

```js
service.patch(null, { items: [] }, { query: {UID:"XXX12345"} });
```

For this to work the `multi` option during service initialization has to be set to `[ 'patch' ]` or `true`.

**Comment by sujeetbuddiga** [comment]
Thanks @daffl  for the info :D
