### ISSUE TITLE
how to wait for all models to be ready?

### ISSUE THREAD

**Issue by Freundschaft** [feathersjs-ecosystem/feathers-mongodb#158]
right now I have my services set up like this according to the feathers generator:

```
const { Service } = require('feathers-mongodb');

exports.AdminAction = class AdminAction extends Service {
  constructor(options, app) {
    super(options);

    app.get('mongoClient').then(db => {
      this.Model = db.collection('admin-actions');
    });
  }
};
```

This works, but when I try to run tests, my problem is, that during application start, the models are not set yet, because the promise hasn't resolved yet. This makes all my tests fail, because they can't access the model in order to run database queries.

What is the recommended solution for this scenario?

Thanks & Best Regards

**Comment by Freundschaft** [comment]
I can see that this is somehow related to this issue on feathers: https://github.com/feathersjs/feathers/issues/509

**Comment by daffl** [comment]
In your tests you should be able to

```js
before(async () => {
  await app.get('mongoClient');
});
```

**Comment by Freundschaft** [comment]
Thanks, that worked!
