### ISSUE TITLE
Aggregation pipeline for patch

### ISSUE THREAD

**Issue by PowerMogli** [feathersjs-ecosystem/feathers-mongodb#178]
According to this [link](https://stackoverflow.com/a/56551655) MongoDB 4.2 supports an aggregation pipeline, allowing the update/creation of a field based on another field.

What do I want to do, you ask? A document in our database looks pseudo-moderate like this { status: 1}. 

I want to update only this documents that have status 1 to status 5.

Is this possible with feathers-mongodb?

**Comment by marshallswain** [comment]
This will work if you set the `multi` option to true before the query.
```js
const params = { query: { status: 1 } }

app.service('todos').patch(null, { status: 5 }, params)
```
