### ISSUE TITLE
Await setting the model before continuing 

### ISSUE THREAD

**Issue by SeverinNovack** [feathersjs-ecosystem/feathers-mongodb#184]
### Steps to reproduce

I am currently trying to create a log service in TypeScript, where I put every log I receive into a mongoDB. I am using the feathers-mongodb adapter und generated the service via the generator.

The code of the mongodb.ts file is the following:
```
import { MongoClient } from 'mongodb';
import { Application } from './declarations';

export default function (app: Application) {
  const connection = app.get('mongodb');
  const database = connection.substr(connection.lastIndexOf('/') + 1);
  const mongoClient = MongoClient.connect(connection, { useNewUrlParser: true })
    .then(client => client.db(database));
  
  app.set('mongoClient', mongoClient);

  mongoClient.then(db => {
    db.createCollection('log', {strict: true}, function(error, collection) {
      if(error) {
        console.log(error);
      }
      else {
        console.log(collection);
      }
    });
  });
}
```

The code of the log.class.ts file is the following:
```
import { Db } from 'mongodb';
import { Service, MongoDBServiceOptions } from 'feathers-mongodb';
import { Application } from '../../declarations';

export class Log extends Service {
  constructor(options: Partial<MongoDBServiceOptions>, app: Application) {
    super(options);

    app.get('mongoClient').then((db: any) => {
      this.Model = db.collection('log');
    });
  }
};
```

I have a custom format for my logging and am using winston as a logger, thus I choose to call the service.create method in the formatter. Here a shortened version of my logger.ts file:
```
import { createLogger, format, transports } from 'winston';
const { timestamp, printf } = format;
import * as winston from 'winston';
import 'winston-daily-rotate-file';
import { Application } from './declarations';


export default class LoggerCreator {
  
  private logConfig: any;
  private app: Application;

  constructor(app: Application) {
    this.logConfig = app.get('logging');
    this.app = app;
    this.setTransports();
  }

 myFormat = printf(({ level, message, timestamp }) => {
    this.app.service('log').create({
      message: message,
      level: level,
      timestamp: timestamp
    });
    return `${timestamp} [${level}]: ${message}`;
  });

 generalLogger = createLogger({
    level: 'info',
    format: format.combine(
      timestamp(),
      this.myFormat
    )
 });
}
```

The problem I have is, that when I .then in the class file to set the model, it jumps out of the constructor as it is supposed to be asynchronous. Thus when the first log message arrives ('the feathers application has started listening on ...') the model is not set yet and I get an undefined error on the service('log').create(...).
I have tried changing the code to Promises and using async/await but sadly it did not work. There surely must be a way to easily wait for the model to be set that I am just missing.
It could be related to https://github.com/feathersjs/feathers/issues/509 but I am not really sure about that.

### Expected behavior
The code should wait for the constructor to finish.

### Actual behavior
When calling .then on the mongoClient the code jumps out of the constructor and thus continues without the model being set yet.

### System configuration

**Module versions** (especially the part that's not working):
"feathers-mongodb": "^6.1.0"
"mongodb": "^3.5.9"
"typescript": "^3.9.5"

**NodeJS version**:
v12.13.1

**Operating System**:
Windows 10

**Module Loader**:
"npm": "6.12.1"

**Comment by daffl** [comment]
Feathers 5 will allows asynchronous setup which should make this quite a bit easier.

**Comment by daffl** [comment]
This has been done now, you can try it by selecting MongoDB and [following the new guide](https://feathersjs.com/guides/basics/generator.html).
