### ISSUE TITLE
Multi-tenancy support?

### ISSUE THREAD

**Issue by svile** [feathersjs-ecosystem/feathers-mongodb#193]
Given the original example to `feathers-mongodb` (also pasted here), I take it that `Model` instances passed to a `service` function are tied to a predefined location in the database i.e. `database\collection` below. Is it possible for the `database` portion to be dynamically set before making each request thus creating a multi-tenancy approach? Is this supported and if so how would it be achieved?

```const MongoClient = require('mongodb').MongoClient;
const service = require('feathers-mongodb');

MongoClient.connect('mongodb://localhost:27017/feathers').then(client => {
  app.use('/messages', service({
    Model: client.db('feathers').collection('messages')
  }));
  app.use('/messages', service({ Model, id, events, paginate }));
});```

**Comment by daffl** [comment]
This is possible with the [v5 @feathersjs/mongodb](https://feathersjs.com/api/databases/mongodb.html) adapter by passing the model on a request basis as as `params.adapter = { Model }`
