### ISSUE TITLE
Error when upgrade package mongodb to 4.0.1

### ISSUE THREAD

**Issue by 001123** [feathersjs-ecosystem/feathers-mongodb#194]
After upgrade package mongodb to 4.0.1 when I call API `authentication` 
it'll show an error
![image](https://user-images.githubusercontent.com/32441266/126577525-df4154ec-bffa-4cd0-a15f-623a1498a051.png)
When I back to 3.6.1 it works normally.
I don't know why it happens.

**Comment by Noobulater** [comment]
The issue here is in the index.js file
https://github.com/feathersjs-ecosystem/feathers-mongodb/compare/master...Noobulater:patch-1

**Comment by 001123** [comment]
Thanks @Noobulater, wait for next update :D

**Comment by daffl** [comment]
Released as v6.3.1
