### ISSUE TITLE
Multi create/patch/remove performance

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs-ecosystem/feathers-mongodb#219]
When using `multi: true`, the `create` method is slow. See: https://discord.com/channels/509848480760725514/1049386346030047293

Solutions
- This line: https://github.com/feathersjs-ecosystem/feathers-mongodb/blob/c8e894cd433b39e5dc92ac824a983944768d25eb/lib/index.js#L219 should probably use { _id: { $in: [result.insertedIds] } } 
- Implement some `$returning: false` or `$limit: 0` to disable Feathers from returning results.

**Comment by daffl** [comment]
I think this will be addressed via https://github.com/feathersjs/feathers/pull/2945 - closing this issue to archive this repository since it has moved.
